// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

// Your web app's Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBRFzwULCldAPvEoCl9Oe7pbSZ2P9VIUeo",
      authDomain: "potent-howl-228108.firebaseapp.com",
      databaseURL: "https://potent-howl-228108.firebaseio.com",
      projectId: "potent-howl-228108",
      storageBucket: "potent-howl-228108.appspot.com",
      messagingSenderId: "319754315071",
      appId: "1:319754315071:web:7d6c51a4a185849651df8a");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3UOnYS71UxbuyjJmgi08rkxKamjH3kwE',
    appId: '1:659194624554:android:2bab1368d4992ae0d56153',
    messagingSenderId: '659194624554',
    projectId: 'mit-app-inventor-bff1c',
    databaseURL: 'https://mit-app-inventor-bff1c-default-rtdb.firebaseio.com',
    storageBucket: 'mit-app-inventor-bff1c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByCIaA4n4JgmZDTCTvWU8FhKu6IokpmAw',
    appId: '1:659194624554:ios:1220bef93b2cb0b1d56153',
    messagingSenderId: '659194624554',
    projectId: 'mit-app-inventor-bff1c',
    databaseURL: 'https://mit-app-inventor-bff1c-default-rtdb.firebaseio.com',
    storageBucket: 'mit-app-inventor-bff1c.appspot.com',
    iosBundleId: 'com.example.carmeltennis',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByCIaA4n4JgmZDTCTvWU8FhKu6IokpmAw',
    appId: '1:319754315071:ios:81a28232c3ae39a951df8a',
    messagingSenderId: '659194624554',
    projectId: 'mit-app-inventor-bff1c',
    databaseURL: 'https://mit-app-inventor-bff1c-default-rtdb.firebaseio.com',
    storageBucket: 'mit-app-inventor-bff1c.appspot.com',
    iosBundleId: 'com.carmeltennisMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbAzSgmbgIGU-Ay5geELsgTaMD4n30kSo',
    appId: '1:659194624554:web:e9bd938df437dad6d56153',
    messagingSenderId: '659194624554',
    projectId: 'mit-app-inventor-bff1c',
    authDomain: 'mit-app-inventor-bff1c.firebaseapp.com',
    databaseURL: 'https://mit-app-inventor-bff1c-default-rtdb.firebaseio.com',
    storageBucket: 'mit-app-inventor-bff1c.appspot.com',
  );
}
